version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: 
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:-guest}"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 2s
      retries: 12

  producer:
    build: ./producer
    container_name: producer
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    # environment:
    #   - RABBITMQ_HOST=rabbitmq
    env_file: 
      - ./.env

  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    # environment:
    #   - RABBITMQ_HOST=rabbitmq
    env_file: 
      - ./.env
